---
- name: Custom tools - run process once or notify
  copy:
    src: run-process-once-or-notify.sh
    dest: "{{ ansible_env.HOME }}/bin/run-process-once-or-notify"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0740

- name: GNOME Terminal - install
  package:
    name: gnome-terminal
    state: present
  become: yes

- name: GNOME Terminal - dark theme
  dconf:
    key: /org/gnome/terminal/legacy/theme-variant
    value: "'dark'"

- name: GNOME Terminal - use tabs
  dconf:
    key: /org/gnome/terminal/legacy/new-terminal-mode
    value: "'tab'"

- name: GNOME Terminal - default terminal open once
  dconf:
    key: /org/gnome/desktop/applications/terminal/exec
    value: "'{{ ansible_env.HOME }}/bin/run-process-once-or-notify'"

- name: GNOME Terminal - default terminal on full screen
  dconf:
    key: /org/gnome/desktop/applications/terminal/exec-arg
    value: "'gnome-terminal --full-screen --wait'"

- name: GNOME Terminal - open with Ctrl+Alt+T (prepare)
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"

- name: GNOME Terminal - open with Ctrl+Alt+T (name)
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
    value: "'GNOME Terminal'"

- name: GNOME Terminal - open with Ctrl+Alt+T (command)
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
    value: "'{{ ansible_env.HOME }}/bin/run-process-once-or-notify gnome-terminal --full-screen --wait'"

- name: GNOME Terminal - open with Ctrl+Alt+T (binding)
  dconf:
    key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
    value: "'<Primary><Alt>t'"

- name: Install used GNOME apps
  package:
    name:
      - baobab # Disk usage analyzer
      - eog # Eye of GNOME
      - evince # PDF
      - file-roller # archives
      - gedit # text editor
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-characters
      - gnome-photos
      - gnome-screenshot
      - gnome-software
      - gnome-system-monitor
      - gnome-weather
      - nautilus # file explorer
    state: present
  become: yes

- name: Uninstall unused GNOME apps, Evolution, Cheese, Rhytmbox and Simple Scan
  package:
    name:
      - evolution
      - cheese
      - gnome-boxes
      - gnome-contacts
      - gnome-documents
      - gnome-maps
      - rhythmbox
      - simple-scan
    state: absent
  become: yes

- name: RPM Fusion free
  package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    state: present
  become: yes

- name: Media codecs
  package:
    name:
      - ffmpeg # for Firefox
      - gstreamer
      - gstreamer-ffmpeg
      - gstreamer1-plugin-openh264
      - openh264
      - gstreamer1-libav
    state: present
  become: yes
