---
- name: Uninstall unused GNOME apps, Evolution, Cheese, Rhytmbox and Simple Scan
  package:
    name:
      - evolution
      - cheese
      - gnome-boxes
      - gnome-contacts
      - gnome-documents
      - gnome-maps
      - rhythmbox
      - simple-scan
    state: absent
  become: yes

- name: Deja Dup
  package:
    name: deja-dup
    state: present
  become: yes

- name: RPM Fusion free
  package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    state: present
  become: yes

- name: Media codecs
  package:
    name:
      - ffmpeg # for Firefox
      - gstreamer
      - gstreamer-ffmpeg
      - gstreamer1-plugin-openh264
      - openh264
      - gstreamer1-libav
    state: present
  become: yes
