---
# https://docs.docker.com/install/linux/docker-ce/fedora/
- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    state: present
  become: yes

- name: Install Docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    state: present
  become: yes

# https://docs.docker.com/install/linux/linux-postinstall/
- name: Create "docker" group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: "{{ system_user }}"
    groups: docker
    append: yes
  become: yes
  notify: "group change message"
