---
- name: Add Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add Fedora repository
  flatpak_remote:
    name: fedora
    state: present
    flatpakrepo_url: oci+https://registry.fedoraproject.org
    method: user

#- name: Install Telegram and Slack
#  flatpak:
#    name:
#      - org.telegram.desktop
#      - com.slack.Slack
#    state: present
#    remote: flathub
#    method: user

- name: Install GIMP in Flatpak
  flatpak:
    name: org.gimp.GIMP
    state: present
    remote: flathub
    method: user

- name: Install IDEA in Flatpak
  flatpak:
    name: com.jetbrains.IntelliJ-IDEA-Community
    state: present
    remote: flathub
    method: user

- name: Install PyCharm in Flatpak
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
    remote: flathub
    method: user

- name: Install Firefox in Flatpak
  flatpak:
    name: org.mozilla.Firefox
    state: present
    remote: fedora
    method: user

- name: Keep only one .desktop file for Firefox
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.Firefox/current/active/files/share/applications/org.mozilla.Firefox.desktop"
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.Firefox/current/active/export/share/applications/org.mozilla.Firefox.desktop"

- name: Install media codecs for Firefox
  flatpak:
    name: org.freedesktop.Platform.ffmpeg
    state: present
    remote: flathub
    method: user
