---
- name: Add Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Add unofficial Firefox repository
  flatpak_remote:
    name: org.mozilla.FirefoxRepo
    state: present
    flatpakrepo_url: https://firefox-flatpak.mojefedora.cz/org.mozilla.FirefoxRepo.flatpakrepo
    method: user

#- name: Install Telegram and Slack
#  flatpak:
#    name:
#      - org.telegram.desktop
#      - com.slack.Slack
#    state: present
#    remote: flathub
#    method: user

- name: Install GIMP in Flatpak
  flatpak:
    name: org.gimp.GIMP
    state: present
    remote: flathub
    method: user

- name: Install IDEA in Flatpak
  flatpak:
    name: com.jetbrains.IntelliJ-IDEA-Community
    state: present
    remote: flathub
    method: user

- name: Install Firefox Nightly in Flatpak
  flatpak:
    name: org.mozilla.FirefoxNightly
    state: present
    remote: org.mozilla.FirefoxRepo
    method: user

- name: Keep only one .desktop file for Firefox Nightly
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.FirefoxNightly/current/active/files/share/applications/org.mozilla.FirefoxNightly.desktop"
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.FirefoxNightly/current/active/export/share/applications/org.mozilla.FirefoxNightly.desktop"

- name: Install media codecs for Firefox
  flatpak:
    name: org.freedesktop.Platform.ffmpeg
    state: present
    remote: flathub
    method: user
