---
- name: "Setup my Fedora"
  hosts: localhost
  connection: local
  vars:
    system_user: michal
    system_user_full_name: Michal Stanke # gnome-settings
    system_user_email: michal@stanke.cz # gnome-settings
    git_user_full_name: Michal Stanke # developer/common
    git_user_email: michal@stanke.cz # developer/common
    git_user_signingkey: E0079E8F # developer/common; GPG key
    hg_user_full_name: Michal Stanke # developer/common
    hg_user_email: mstanke@mozilla.cz # developer/common
    maven_version: 3.6.3 # developer/java
    fedora_version: 33 # apps/repo
    firefox_locale: cs # apps/custom

  pre_tasks:
    - name: ansible-lint - install
      package:
        name: python3-ansible-lint
        state: present
      become: yes

    - name: ansible-lint - run
      command: ansible-lint main.yml
      args:
        creates: nothing # noqa 301
      changed_when: false

    # dconf module dependency, see https://docs.ansible.com/ansible/latest/modules/dconf_module.html#notes
    - name: Python psutil
      package:
        name: python3-psutil
        state: present
      become: yes

  roles:
    - firewall
    - system
    - developer/common
    - developer/python
    - developer/ruby
    - developer/java
    - developer/rust
    - developer/javascript
    - shell
    - apps/flatpak
    - apps/repo
    - apps/custom
    - print
