---
- name: Create Firefox Nightly installation directory
  file:
    path: /opt/firefox/
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"
  become: yes

- name: Extract Firefox Nightly tarball to installation directory
  unarchive:
    src: "https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang={{ locale }}"
    dest: /opt/firefox/
    copy: no
    creates: /opt/firefox/firefox

- name: Prepare Nightly logo for shortcut
  copy:
    src: firefox-logo-nightly.svg
    dest: /opt/firefox/

- name: Create shortcut for Firefox Nightly
  copy:
    src: nightly.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"

- name: Uninstall Firefox from distro repository
  package:
    name: firefox
    state: absent
  become: yes

# https://netcologne.dl.sourceforge.net/project/freemind/freemind/1.0.1/freemind-bin-max-1.0.1.zip
- name: Create FreeMind installation directory
  file:
    path: /opt/freemind/
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"
  become: yes

- name: Extract FreeMind archive to installation directory
  unarchive:
    src: https://netcologne.dl.sourceforge.net/project/freemind/freemind/1.0.1/freemind-bin-max-1.0.1.zip
    dest: /opt/freemind/
    copy: no
    creates: /opt/freemind/freemind.sh

- name: Make FreeMind run script executable
  file:
    path: /opt/freemind/freemind.sh
    mode: 0744

- name: Prepare FreeMind logo for shortcut
  copy:
    src: freemind-logo.png
    dest: /opt/freemind/

- name: Create shortcut for FreeMind
  copy:
    src: freemind.desktop
    dest: "{{ ansible_env.HOME }}/.local/share/applications/"

- name: mozregression
  pip:
    name: mozregression
    state: present
    executable: pip2
    extra_args: --user

- name: Atom
  package:
    name: "https://atom.io/download/rpm" # latest
    state: present
  become: yes
