---
- name: Uninstall unused GNOME apps, Evolution, Cheese, Rhytmbox and Simple Scan
  dnf:
    name:
      - evolution
      - cheese
      - gnome-contacts
      - gnome-documents
      - gnome-maps
      - rhythmbox
      - simple-scan
    state: absent
  become: yes

- name: Install RPM Fusion free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    state: present
  become: yes

- name: Install media codecs
  dnf:
    name:
      - ffmpeg # for Firefox
      - gstreamer
      - gstreamer-ffmpeg
      - gstreamer1-plugin-openh264
      - openh264
      - gstreamer1-libav
    state: present
  become: yes

- name: Install Deja Dup
  dnf:
    name: deja-dup
    state: present
  become: yes

# https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
# Cleanup
- name: Remove VirtualBox repository
  yum_repository:
    name: virtualbox
    description: Fedora - VirtualBox
    baseurl: https://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    state: absent
  become: yes

# Cleanup
- name: Uninstall VirtualBox
  dnf:
    name:
      - VirtualBox
      - VirtualBox-kmodsrc
      - VirtualBox-server
      - akmod-VirtualBox
      - kmod-VirtualBox
      - virtualbox-guest-additions
    state: absent
  become: yes
