---
- name: User - copy wallpaper to home
  copy:
    src: Firefox-2019-Logo-Nightly.png
    dest: "{{ ansible_env.HOME }}/.wallpaper.jpg"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0640

- name: User - configure wallpaper
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ ansible_env.HOME }}/.wallpaper.jpg'"

- name: User - set full name
  user:
    name: "{{ system_user }}"
    comment: "{{ system_user_full_name }}"
  become: yes

- name: User - profile picture
  get_url:
    url: "https://www.gravatar.com/avatar/{{ system_user_email | hash('md5') }}?s=192"
    dest: "{{ ansible_env.HOME }}/.face"

- name: User - automatic login
  blockinfile:
    path: /etc/gdm/custom.conf
    insertafter: "^\\[daemon\\]$"
    block: |
      AutomaticLoginEnable=True
      AutomaticLogin={{ system_user }}
  become: yes

- name: Lock screen when lid is closed
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^HandleLidSwitch="
    line: "HandleLidSwitch=lock"
    insertafter: "^#HandleLidSwitch="
  become: yes
  notify: "lock screen message"

- name: Night light (red shift)
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"

- name: Alt+Tab (and above-Tab) on current workspace only
  dconf:
    key: /org/gnome/shell/app-switcher/current-workspace-only
    value: "true"

- name: Touchpad tap as click
  dconf:
    key: /org/gnome/settings-daemon/peripherals/touchpad/tap-to-click
    value: "true"
  notify: "touchpad change message"

- name: Dash favourite applications
  dconf:
    key: /org/gnome/shell/favorite-apps
    value: "['nightly.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'net.cozic.joplin_desktop.desktop']"

- name: Nautilus - default view as list
  dconf:
    key: /org/gnome/nautilus/preferences/default-folder-viewer
    value: "'list-view'"

- name: Nautilus - open folders in place (tree view)
  dconf:
    key: /org/gnome/nautilus/list-view/use-tree-view
    value: "true"

- name: Nautilus - sort folders before files
  dconf:
    key: /org/gtk/settings/file-chooser/sort-directories-first
    value: "true"

- name: GNOME extensions - disable
  dconf:
    key: /org/gnome/shell/disable-user-extensions
    value: "true"

- name: exFAT support
  package:
    name:
      - fuse-exfat
      - exfat-utils
    state: present
  become: yes
