---
- name: Install git
  package:
    name: git
    state: present
  become: yes

- name: .gitconfig - email
  git_config:
    name: "user.email"
    value: "{{ system_user_email }}"
    scope: global

- name: .gitconfig - name
  git_config:
    name: "user.name"
    value: "{{ system_user_full_name }}"
    scope: global

- name: .gitconfig - push default
  git_config:
    name: "push.default"
    value: "simple"
    scope: global

- name: .gitconfig - signing key
  git_config:
    name: "user.signingkey"
    value: "{{ system_user_gpg_key }}"
    scope: global

- name: .gitconfig - sign commits
  git_config:
    name: "gpg.program"
    value: "gpg2"
    scope: global

- name: .gitconfig - sign commits
  git_config:
    name: "commit.gpgsign"
    value: "true"
    scope: global

- name: Create global git ignore file
  copy:
    src: gitignore_global
    dest: "{{ ansible_env.HOME }}/.gitignore_global"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0600

- name: .gitconfig global git ignore file
  git_config:
    name: "core.excludesfile"
    value: "{{ ansible_env.HOME }}/.gitignore_global"
    scope: global
