---
- name: Flatpak - Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Flatpak - Fedora repository
  flatpak_remote:
    name: fedora
    state: present
    flatpakrepo_url: oci+https://registry.fedoraproject.org
    method: user

- name: Deja Dup - install
  flatpak:
    name: org.gnome.DejaDup
    state: present
    remote: flathub
    method: user

- name: Deja Dup - configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.var/app/org.gnome.DejaDup/config/glib-2.0/settings/"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0700

- name: Deja Dup - configuration
  blockinfile:
    path: "{{ ansible_env.HOME }}/.var/app/org.gnome.DejaDup/config/glib-2.0/settings/keyfile"
    create: yes
    block: |
      [org/gnome/deja-dup]
      backend='drive'

      include-list=['$HOME']
      exclude-list=['$TRASH', '$DOWNLOAD', '$HOME/.cache', '$HOME/.var', '$HOME/.local/share/flatpak', '$HOME/repos', '$HOME/sshfs']

      periodic=true
      periodic-period=7
      delete-after=182

      [org/gnome/deja-dup/drive]
      folder='{{ ansible_hostname }}'
      uuid='0C42C54C42C53AEA'
      icon='. GThemedIcon drive-harddisk-usb drive-harddisk drive drive-harddisk-usb-symbolic drive-harddisk-symbolic drive-symbolic'
      name='My Passport'

- name: Riot
  flatpak:
    name: im.riot.Riot
    state: present
    remote: flathub
    method: user

- name: Fractal
  flatpak:
    name: org.gnome.Fractal
    state: present
    remote: flathub
    method: user

- name: GIMP
  flatpak:
    name: org.gimp.GIMP
    state: present
    remote: flathub
    method: user

- name: IntelliJ IDEA
  flatpak:
    name: com.jetbrains.IntelliJ-IDEA-Community
    state: present
    remote: flathub
    method: user

- name: PyCharm
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
    remote: flathub
    method: user

- name: Atom - install
  flatpak:
    name: io.atom.Atom
    state: present
    remote: flathub
    method: user

- name: Atom - alias
  blockinfile:
    path: "{{ ansible_env.HOME }}/bin/atom"
    create: yes
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0740
    marker: "#{mark}"
    marker_begin: "!/bin/sh"
    block: "flatpak run io.atom.Atom $@"

- name: Visual Studio Code
  flatpak:
    name: com.visualstudio.code.oss
    state: present
    remote: flathub
    method: user

- name: Firefox beta - install
  flatpak:
    name: https://flathub.org/beta-repo/appstream/org.mozilla.firefox.flatpakref
    state: present
    method: user

- name: Firefox - media codecs
  flatpak:
    name: org.freedesktop.Platform.ffmpeg
    state: present
    remote: flathub
    method: user

- name: Spotify
  flatpak:
    name: com.spotify.Client
    state: present
    remote: flathub
    method: user
