---
- name: Flatpak - Flathub repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Flatpak - Fedora repository
  flatpak_remote:
    name: fedora
    state: present
    flatpakrepo_url: oci+https://registry.fedoraproject.org
    method: user

- name: Deja Dup - install
  flatpak:
    name: org.gnome.DejaDup
    state: present
    remote: flathub
    method: user

- name: Deja Dup - configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.var/app/org.gnome.DejaDup/config/glib-2.0/settings/"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0700

- name: Deja Dup - configuration file
  template:
    src: deja-dup-keyfile
    dest: "{{ ansible_env.HOME }}/.var/app/org.gnome.DejaDup/config/glib-2.0/settings/keyfile"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0600

- name: GIMP
  flatpak:
    name: org.gimp.GIMP
    state: present
    remote: flathub
    method: user

- name: IntelliJ IDEA
  flatpak:
    name: com.jetbrains.IntelliJ-IDEA-Community
    state: present
    remote: flathub
    method: user

- name: PyCharm
  flatpak:
    name: com.jetbrains.PyCharm-Community
    state: present
    remote: flathub
    method: user

- name: Atom
  flatpak:
    name: io.atom.Atom
    state: present
    remote: flathub
    method: user

- name: Firefox beta - install
  flatpak:
    name: https://flathub.org/beta-repo/appstream/org.mozilla.firefox.flatpakref
    state: present
    method: user

- name: Firefox - media codecs
  flatpak:
    name: org.freedesktop.Platform.ffmpeg
    state: present
    remote: flathub
    method: user

- name: Keep only one .desktop file for Firefox
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.firefox/current/active/files/share/applications/org.mozilla.firefox.desktop"
    - "{{ ansible_env.HOME }}/.local/share/flatpak/app/org.mozilla.firefox/current/active/export/share/applications/org.mozilla.firefox.desktop"

- name: Spotify
  flatpak:
    name: com.spotify.Client
    state: present
    remote: flathub
    method: user
